### ISSUE TITLE
Add my Dataverse repository: {Data Station Archaeology}

### ISSUE THREAD

**Issue by WittenbergM** [IQSS/dataverse-installations#161]
*All information shared will be displayed on the map unless otherwise indicated*

**Name of repository:Data Station Archaeology**

**Homepage URL of repository:https://dans.knaw.nl/nl/data-stations/archaeology/**

**Location of the repository: (Anna van Saksenlaan 51, 2593 HW The Hague, The Netherlands)**

**Year when repository started operating:2022**

*The following isn't required but is nice to have:*

**A short description (few sentences) about the repository:
Data repository to deposit and search for data within the field of archaeology in the Netherlands **

**Email address of repository contact (won't be displayed on the map):
contact person hella.hollander@dans.knaw.nl**

**DOI authority (such as 10.26193; if applicable; won't be displayed on the map):10.17026**

**Link to successful [Core Trust Seal](https://www.coretrustseal.org) application:**

**Comment by jggautier** [comment]
Hi @WittenbergM. Thanks for letting us know about this repository.

Should the homepage be https://archaeology.datastations.nl, instead? I think the Dataverse metrics page at https://dataverse.org/metrics uses the homepage URL so that it can use the Dataverse APIs to get metrics from different Dataverse installations. And I can't use the APIs with https://dans.knaw.nl/nl/data-stations/archaeology.

For example, https://dans.knaw.nl/nl/data-stations/archaeology/api/info/version doesn't work, whereas https://archaeology.datastations.nl/api/info/version does work.

If both sites point to the same repository and the same data, and you'd like people to go to URL you provided (https://dans.knaw.nl/nl/data-stations/archaeology), then maybe we should start recording two URLs: a homepage URL and a URL that can be used with the Dataverse APIs to get metrics.

Pinging @pdurbin and @donsizemore who work on that metrics page.

**Comment by pdurbin** [comment]
https://dans.knaw.nl/nl/data-stations/archaeology/ should go in the `about_url` column in the spreadsheet. This URL becomes the "More..." link in the map. Here's an example from DataverseNL:

![Screen Shot 2022-08-31 at 2 55 45 PM](https://user-images.githubusercontent.com/21006/187760520-6eab097c-3a38-4cf7-bfd4-e74e9950560d.png)

And yes, the hostname should be archaeology.datastations.nl so we can collect metrics, etc.

@WittenbergM instead of hella.hollander@dans.knaw.nl is there a non-personal email address we can use? A more generic address that goes to a group of people, I mean. If not, it's fine, but a generic address like support@dataverse.harvared.edu is preferred.

**Comment by jggautier** [comment]
@pdurbin, are you thinking that people who want to visit the repository should click on the "More" link, such as:

![more_link](https://user-images.githubusercontent.com/18374574/187762920-2f895f4c-2b03-4583-823b-b930852b6c68.png)

and not the first link in the popup that's the name of the repository, such as:

![repository_link](https://user-images.githubusercontent.com/18374574/187763011-11556cca-c18f-4bdf-982f-c2a990076108.png)

**Comment by pdurbin** [comment]
@jggautier this is where the links go:

![187760520-6eab097c-3a38-4cf7-bfd4-e74e9950560d](https://user-images.githubusercontent.com/21006/187778932-75a69ccc-fea3-41d0-b5e3-04b81ba8920b.png)

**Comment by jggautier** [comment]
Thanks, yes that's how we mean it to work.

I think it would be helpful to learn where @WittenbergM (and perhaps the admins of other repositories) expect people to be taken when they click on the first link, what you've labelled "installation."

What do you think @WittenbergM?

**Comment by jggautier** [comment]
@4tikhonov wrote in a Slack conversation that we should use https://archaeology.datastations.nl/ as the "Homepage URL of repository". That's where people will go when they click on the "Data Station Archaeology" link on the Dataverse map.

**Comment by WittenbergM** [comment]
This is fine with me

 

Best, Marion

 

From: Julian Gautier ***@***.***>
Reply to: IQSS/dataverse-installations ***@***.***>
Date: Thursday, 1 September 2022 at 18:17
To: IQSS/dataverse-installations ***@***.***>
Cc: Marion Wittenberg ***@***.***>, Mention ***@***.***>
Subject: Re: [IQSS/dataverse-installations] Add my Dataverse repository: {Data Station Archaeology} (Issue #161)

 

@4tikhonov wrote in a Slack conversation that we should use https://archaeology.datastations.nl/ as the "Homepage URL of repository". That's where people will go when they click on the "Data Station Archaeology" link on the Dataverse map.

**Comment by WittenbergM** [comment]
Hi Julian,

 

I think the root of the installation is fine.

In the case of our archeology datas tation: https://archaeology.datastations.nl/

 

Best, Marion

 

From: Julian Gautier ***@***.***>
Reply to: IQSS/dataverse-installations ***@***.***>
Date: Wednesday, 31 August 2022 at 23:25
To: IQSS/dataverse-installations ***@***.***>
Cc: Marion Wittenberg ***@***.***>, Mention ***@***.***>
Subject: Re: [IQSS/dataverse-installations] Add my Dataverse repository: {Data Station Archaeology} (Issue #161)

 

Thanks, yes that's how we mean it to work.

I think it would be helpful to learn where @WittenbergM (and perhaps the admins of other repositories) expect people to be taken when they click on the first link, what you've labelled "installation."

What do you think @WittenbergM?

**Comment by WittenbergM** [comment]
Hi Philipp,

 

I am sorry to give you the wrong url

The right one is https://archaeology.datastations.nl/

 

The link on the map doesn’t work.

Because you used http://https//archaeology.datastations.nl

 

A direct email address is ***@***.***

 

Best, Marion

 

 

From: Philip Durbin ***@***.***>
Reply to: IQSS/dataverse-installations ***@***.***>
Date: Wednesday, 31 August 2022 at 21:01
To: IQSS/dataverse-installations ***@***.***>
Cc: Marion Wittenberg ***@***.***>, Mention ***@***.***>
Subject: Re: [IQSS/dataverse-installations] Add my Dataverse repository: {Data Station Archaeology} (Issue #161)

 

https://dans.knaw.nl/nl/data-stations/archaeology/ should go in the about_url column in the spreadsheet. This URL becomes the "More..." link in the map. Here's an example from DataverseNL:

And yes, the hostname should be archaeology.datastations.nl so we can collect metrics, etc.

@WittenbergM instead of ***@***.*** is there a non-personal email address we can use? A more generic address that goes to a group of people, I mean. If not, it's fine, but a generic address like ***@***.*** is preferred.

**Comment by WittenbergM** [comment]
Hi Julian,

 

Yes, please use https://archaeology.datastations.nl

 

Best, Marion

 

From: Julian Gautier ***@***.***>
Reply to: IQSS/dataverse-installations ***@***.***>
Date: Wednesday, 31 August 2022 at 16:52
To: IQSS/dataverse-installations ***@***.***>
Cc: Marion Wittenberg ***@***.***>, Mention ***@***.***>
Subject: Re: [IQSS/dataverse-installations] Add my Dataverse repository: {Data Station Archaeology} (Issue #161)

 

Hi @WittenbergM. Thanks for letting us know about this repository.

Should the homepage be https://archaeology.datastations.nl, instead? I think the Dataverse metrics page at https://dataverse.org/metrics uses the homepage URL so that it can use the Dataverse APIs to get metrics from different Dataverse installations. And I can't use the APIs with https://dans.knaw.nl/nl/data-stations/archaeology.

For example, https://dans.knaw.nl/nl/data-stations/archaeology/api/info/version doesn't work, whereas https://archaeology.datastations.nl/api/info/version does work.

If both sites point to the same repository and the same data, and you'd like people to go to URL you provided (https://dans.knaw.nl/nl/data-stations/archaeology), then maybe we should start recording two URLs: a homepage URL and a URL that can be used with the Dataverse APIs to get metrics.

Pinging @pdurbin and @donsizemore who work on that metrics page.
