### ISSUE TITLE
Documentation: Installation Guides Add More Info on Getting Installations on the Map

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse-installations#17]
The map has instructions:

To add your installation to the map, please follow the [instructions in the Dataverse documentation.](http://guides.dataverse.org/en/latest/installation/config.html#putting-your-dataverse-installation-on-the-map-at-dataverse-org)

I am proposing that the instructions in the installation doc be more instructive, such as go to the google doc and add your institutions's info.

**Comment by pdurbin** [comment]
@shlake yes! Exactly! Instead of linking to the guides, how do you feel about writing something in this repo that we can link to. You an pick the format. I'm a fan of Markdown but I'm ok with whatever you choose. Would you like to pop into http://chat.dataverse.org sometime to talk about this? Or we could do a phone call or video chat if that's easier.

**Comment by pdurbin** [comment]
@shlake hi! I forget what we decided back when last had a phone call? Something about a wiki? Should this issue be assigned to you? Or do you want me to add more to the README? The good news is that despite the lack of good documentation, we've been able to successfully add installations to the map. 😄 It would be nice to make the process even more clear, especially since the plan is for the process to evolve over time as we work on https://github.com/IQSS/dataverse.org/issues/66

**Comment by shlake** [comment]
@pdurbin After working on the readme and Contributing docs, I think doing a wiki is overkill. This should be "easy", I think it is, as long as all the parts are documented, which are almost there.

Yes, I'll add more to the README, knowing that processes will change? I'll re-look at what needs to be added.

**Comment by pdurbin** [comment]
@shlake famous last words. 😄 

Ok! I assigned it to you. Thanks! Please let me know if I can help at all. Yes, the process will change as we work toward shutting down the miniverse server for https://github.com/IQSS/dataverse.org/issues/66 so it wouldn't hurt to mention that change is coming in the README (encourage people to check back or whatever).

@jggautier heads up that I should have pointed to CONTRIBUTING.md for the `python3 update-data.py` command we ran yesterday. I forgot that @shlake did some great work in ab2e859 and moved it there (with a lot more detail).
