### ISSUE TITLE
Remove dataverse.arch.be from the map

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse-installations#38]
Now that @pdurbin has included code to read "is_active" from main installation file, see #35 

the installation script needs to be run to remove it from "dataverse-installations"

@shlake will do

**Comment by pdurbin** [comment]
@shlake sorry for the confusion! This is done already because pull request #37 has been merged. Here's a screenshot of "files changed" where we can see that dataverse.arch.be was removed:

<img width="1042" alt="Screen Shot 2019-12-06 at 10 25 52 AM" src="https://user-images.githubusercontent.com/21006/70334167-e6454a00-1812-11ea-9913-5d980ea6ceea.png">

**Comment by shlake** [comment]
Thanks. @pdurbin when I first looked at the map, it was still there. I have to remember that github takes awhile to update its web pages.

Will close.

**Comment by pdurbin** [comment]
Yeah, in my experienced it's pretty quick... usually less than two minutes, I'd say. But you're right, it's not immediate.

**Comment by pdurbin** [comment]
When we do add this installations to the map, we should be sure to include its new board: https://github.com/orgs/IQSS/projects/21
