### ISSUE TITLE
add dadosabertos.rnp.br

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-installations#42]
http://dadosabertos.rnp.br has been added to the old map and should be added to the new map as well.

**Comment by pdurbin** [comment]
As I mentioned in standup, when we switched https://dataverse.org from the old miniverse map to the new leaflet map we lost an installation in Brazil ( http://dadosabertos.rnp.br ), dropping from 53 to 52.

I know that @shlake and @jggautier and others have updated the data.json file in this repo before by running the Python script but @djbrooke would like to give it a try so please let him pick up this issue as time allows.

@djbrooke here are the docs (thank you @shlake for working on these!):

- Previewing the map: https://github.com/IQSS/dataverse-installations#viewing-and-updating-the-map
- Updating the map: https://github.com/IQSS/dataverse-installations/blob/master/CONTRIBUTING.md#updating-the-map

**Comment by djbrooke** [comment]
@jggautier @pdurbin @shlake I took a quick look at the docs and I could probably figure it out but I want to better understand the workflow first. Does all of this process just serve to update the https://github.com/IQSS/dataverse-installations/blob/master/data/data.json file which I assume powers the map? If that's the case, why not just make PRs directly against that file?

**Comment by pdurbin** [comment]
@djbrooke sounds like we should document the workflow. I just created an issue for this: #50.

**Comment by djbrooke** [comment]
I worked on this a little on Friday and wasn't able to get it going, and I have a busy week and I'm not able to work on this. :( Someone else should pick it up if they are interested and have capacity.

**Comment by jggautier** [comment]
This installation is added to the old map (the miniverse database) but I've marked it inactive because I'm waiting to hear back from the admin, who said he'll email me when he's ready (https://help.hmdc.harvard.edu/Ticket/Display.html?id=283158). And [the installation home page](https://dataverse.arch.be/) still says it's a test.

The way things are set up, we need to know when an installation is added to the old map (#43) but only if it's marked as active.

Also, before I saw that the installation is marked as inactive in the miniverse database, I tried running the script and got a key error:

<img width="543" alt="Screen Shot 2020-02-03 at 1 40 49 PM" src="https://user-images.githubusercontent.com/18374574/73680754-d7500c00-468a-11ea-9869-e94937f86b92.png">

I added Country (and Continent) to [one of the spreadsheets](https://docs.google.com/spreadsheets/d/1l2R9D1FQy88qVzg2bI6L1LgplmM2l7pnMI80jdiz4fk/edit#gid=639378778) (the two spreadsheets actually didn't have info about this installation) and reran the script, but I get the same key error.

Then saw [these lines](https://github.com/IQSS/dataverse-installations/blob/14ce3afc9436d4194a0c5011059c76e6e72d8dfa/update-data.py#L102) in update_data.py, in the "# Data from miniverse map application" section:
```
i['country'] = mydict[i['hostname']]['country']
i['continent'] = mydict[i['hostname']]['continent']
```

Is the script expecting the miniverse map application to store info about country and continent? It doesn't:

<img width="747" alt="Screen Shot 2020-02-03 at 2 10 26 PM" src="https://user-images.githubusercontent.com/18374574/73682756-06687c80-468f-11ea-8ed6-8932e648d514.png">

**Comment by pdurbin** [comment]
@donsizemore I think @shlake is at an NIH meeting. Do you have capacity to work on this and #49?

**Comment by pdurbin** [comment]
@tcoupin or @lwo you are also welcome to help with this and #49 if you'd like. I **think** you all have access to update the spreadsheets linked from the README. If not, please feel free to request edit access! 😄

**Comment by shlake** [comment]
@pdurbin I can try to fix this. Sorry I haven't been much help lately. I'm at NIH next week.

**Comment by pdurbin** [comment]
@shlake thank you! Please let me know if you need anything! I'll be in chat, etc.

**Comment by shlake** [comment]
@pdurbin there are 3 pull requests that I will look at and merge and then start on this one and #49

**Comment by pdurbin** [comment]
@shlake perfect! Thank you!!

**Comment by shlake** [comment]
@jggautier the script is now working, problem was with the uclovain site. It was on the crowd source doc & old map, BUT not on the IQSS spreadsheet. Once I closed #49 things worked.

@pdurbin BUT am not adding dadosabertos.rnp.br (this issue) just yet. That URL does not resolve.

**Comment by pdurbin** [comment]
@shlake huh. You're right, that installation seems to be down (I'll take you off this issue):

![Screen Shot 2020-02-04 at 10 21 51 AM](https://user-images.githubusercontent.com/21006/73758119-361f8f00-4738-11ea-9aff-3f9e99100388.png)

@jggautier I'm having trouble finding an RT ticket for http://dadosabertos.rnp.br . Can you please take a look?

**Comment by pdurbin** [comment]
@shlake two things.

http://dadosabertos.rnp.br is resolving now. It looks like they're working on getting Dataverse running again. We can give them time to work on this.

Meanwhile, it looks like you've already added http://dadosabertos.rnp.br in 51cc067 which is great.

![Screen Shot 2020-02-04 at 12 42 14 PM](https://user-images.githubusercontent.com/21006/73771153-c9ae8b00-474b-11ea-8e48-7f63f2aa454f.png)

What else do we need? To add the installation to the spreadsheets and add a launch year (#7) of 2019? It looks like I announced it here: https://groups.google.com/d/msg/dataverse-community/4UOFychBqnA/f2IqurALAQAJ . Am I forgetting something? 😄 Do you want to keep working on this? Or should I or someone else pick it up? Thanks. 😄

**Comment by pdurbin** [comment]
@shlake I just created pull request #53  

If you're happy with it, please feel free to merge it. Thanks!
