### ISSUE TITLE
hard to know when the old map has a new installation

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-installations#43]
Yesterday in the community call it was mentioned that a new installation was add to the map (the old map), bringing the total to 53. It turns out it was dadosabertos.rnp.br and I created #42 about this, but it would be nice if we could just run our update script and have it tell us which installation was added to the old map.

**Comment by jggautier** [comment]
What if when people request to be on the map, anyone who gets the request, including me, can ask the Dataverse repository admin to could fill out a Google form that asks for the repository name, description, location and launch year. That form would populate [the spreadsheet](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo) that this script is pulling data from. I'm suggesting a Google form, instead of asking people to edit the spreadsheet, because I think it'll give us more control over how people enter information in the spreadsheet.

Then I think anyone interested in the map(s) could set up a notification alert to be notified whenever changes are made on the spreadsheet. For example, I would set up a notification so that I know when new repositories are added to the new map and I can add them to the old map (while both maps are still being maintained).

What do you all think?

**Comment by pdurbin** [comment]
@jggautier well, technically, the script pulls from three spreadsheets right now.

I'm not opposed to a Google form, but maybe we should wait until we get it add down to one spreadsheet?

My proposed short term solution is pull request #44 which prints out a note to the person running the script like this:

```
$ python3 update-data.py 
On the old map only (should be added): dadosabertos.rnp.br
```
